// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(

    //apiKey: 'AIzaSyCm4SGevAfFGGvSpjjdEt_8t27HakRTbek',
    //appId: '1:585325962794:web:8c64be9cd84185ec528553',
    //messagingSenderId: '585325962794',
    //projectId: 'reusemart-f002c',
    //authDomain: 'reusemart-f002c.firebaseapp.com',
    //storageBucket: 'reusemart-f002c.firebasestorage.app',
  //);

  //static const FirebaseOptions android = FirebaseOptions(
    //apiKey: 'AIzaSyDbybt4eLxreFBCVrKSK5c8GmRkppWIUok',
    //appId: '1:585325962794:android:a257ac105fd932fa528553',
    //messagingSenderId: '585325962794',
    //projectId: 'reusemart-f002c',
    //storageBucket: 'reusemart-f002c.firebasestorage.app',
  //);

  //static const FirebaseOptions ios = FirebaseOptions(
    //apiKey: 'AIzaSyDaY0JxMWJhhGFhcVPAi5zGz9eUlEqfKpM',
    //appId: '1:585325962794:ios:b8b761fdcc5d7de2528553',
    //messagingSenderId: '585325962794',
    //projectId: 'reusemart-f002c',
    //storageBucket: 'reusemart-f002c.firebasestorage.app',

    apiKey: 'AIzaSyDxafFrUJGUqr6sSZxAh7zWSpUcdKm7qwA',
    appId: '1:467562307011:web:1bbbae8c31d548c0083176',
    messagingSenderId: '467562307011',
    projectId: 'reusemart-2d798',
    authDomain: 'reusemart-2d798.firebaseapp.com',
    storageBucket: 'reusemart-2d798.firebasestorage.app',
    measurementId: 'G-HS7RQK0GY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkb9xy-zc7mJR8sYKt_xH0mgfxtsHCfuY',
    appId: '1:467562307011:android:8681f1bd327685e1083176',
    messagingSenderId: '467562307011',
    projectId: 'reusemart-2d798',
    storageBucket: 'reusemart-2d798.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRFxYWjKN-RTbGwV0o3DH9Npyzgbqz19A',
    appId: '1:467562307011:ios:57fc21f8652b8dac083176',
    messagingSenderId: '467562307011',
    projectId: 'reusemart-2d798',
    storageBucket: 'reusemart-2d798.firebasestorage.app',
    iosBundleId: 'com.example.reuseMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    //apiKey: 'AIzaSyDaY0JxMWJhhGFhcVPAi5zGz9eUlEqfKpM',
    //appId: '1:585325962794:ios:b8b761fdcc5d7de2528553',
    //messagingSenderId: '585325962794',
    //projectId: 'reusemart-f002c',
    //storageBucket: 'reusemart-f002c.firebasestorage.app',

    apiKey: 'AIzaSyCRFxYWjKN-RTbGwV0o3DH9Npyzgbqz19A',
    appId: '1:467562307011:ios:57fc21f8652b8dac083176',
    messagingSenderId: '467562307011',
    projectId: 'reusemart-2d798',
    storageBucket: 'reusemart-2d798.firebasestorage.app',
    iosBundleId: 'com.example.reuseMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    //apiKey: 'AIzaSyCm4SGevAfFGGvSpjjdEt_8t27HakRTbek',
    //appId: '1:585325962794:web:d93684ddfcb38160528553',
    //messagingSenderId: '585325962794',
    //projectId: 'reusemart-f002c',
    //authDomain: 'reusemart-f002c.firebaseapp.com',
    //storageBucket: 'reusemart-f002c.firebasestorage.app',

    apiKey: 'AIzaSyDxafFrUJGUqr6sSZxAh7zWSpUcdKm7qwA',
    appId: '1:467562307011:web:491747b6b7bd5350083176',
    messagingSenderId: '467562307011',
    projectId: 'reusemart-2d798',
    authDomain: 'reusemart-2d798.firebaseapp.com',
    storageBucket: 'reusemart-2d798.firebasestorage.app',
    measurementId: 'G-78M8H2X1CN',
  );

}