// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsBa9J_9XCnMJ67Ao50weP3_ONb7UGMBM',
    appId: '1:686617245355:web:a758e918925b39355529ee',
    messagingSenderId: '686617245355',
    projectId: 'reusemart-4735d',
    authDomain: 'reusemart-4735d.firebaseapp.com',
    storageBucket: 'reusemart-4735d.firebasestorage.app',
    measurementId: 'G-EFN16DSVYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL7JsmawaQEWYWzjYeN_HpbSHbRQBcXyE',
    appId: '1:686617245355:android:6627eda2f84d8ef45529ee',
    messagingSenderId: '686617245355',
    projectId: 'reusemart-4735d',
    storageBucket: 'reusemart-4735d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVYSuWnyjIBJ4_oyhLtRWHbL3qN0p10g4',
    appId: '1:686617245355:ios:d7672a2bb4076b695529ee',
    messagingSenderId: '686617245355',
    projectId: 'reusemart-4735d',
    storageBucket: 'reusemart-4735d.firebasestorage.app',
    iosBundleId: 'com.example.reuseMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVYSuWnyjIBJ4_oyhLtRWHbL3qN0p10g4',
    appId: '1:686617245355:ios:d7672a2bb4076b695529ee',
    messagingSenderId: '686617245355',
    projectId: 'reusemart-4735d',
    storageBucket: 'reusemart-4735d.firebasestorage.app',
    iosBundleId: 'com.example.reuseMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsBa9J_9XCnMJ67Ao50weP3_ONb7UGMBM',
    appId: '1:686617245355:web:aa2a17ae29365a205529ee',
    messagingSenderId: '686617245355',
    projectId: 'reusemart-4735d',
    authDomain: 'reusemart-4735d.firebaseapp.com',
    storageBucket: 'reusemart-4735d.firebasestorage.app',
    measurementId: 'G-3MWED2796S',
  );
}
